name: deploy-exc1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
        working-directory: ./exc1
      - name: run lint
        run: npm run lint
        working-directory: ./exc1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
        working-directory: ./exc1
      - name: run test
        run: npm test
        working-directory: ./exc1
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
        working-directory: ./exc1
      - name: run build
        run: npm run build
        working-directory: ./exc1