name: deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
        working-directory: ./exc1
      - name: run lint
        run: npm run lint
        working-directory: ./exc1
      - name: run tests
        run: npm test
        working-directory: ./exc1
      - name: build project
        run: npm run build
        working-directory: ./exc1